version: '3'

networks:
  daas:
    external: false
    name: daas

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: server:node
    container_name: node_container
    ports:
      - "5001:5001"
    networks:
      - daas
    volumes:
      - ./server:/295B/server
    
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: client:react
    container_name: react_container
    ports:
      - "3000:3000"
    networks:
      - daas
    volumes:
    - ./client:/295B/client
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    user: root
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - ./cassandra/schema:/docker-entrypoint-initdb.d
      - 'cassandra_data:/bitnami'
    healthcheck:
      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - daas

  processingServer:
    build:
      context: ./processingServer
      dockerfile: ./Dockerfile
    image: spark:3.1.2
    container_name: spark_container
    ports:
      - "5000:5000"
    networks:
      - daas
    volumes:
      - ./processingServer:/home/jovyan/295B/processingServer
      
volumes:
  cassandra_data:
    driver: local