version: '3'

networks:
  daas:
    external: false
    name: daas

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: server:node
    container_name: node_container
    ports:
      - "5001:5001"
    networks:
      - daas
    links:
      - "processingServer:flaskserver"
    volumes:
      - ./server:/295B/server
    
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: client:react
    container_name: react_container
    ports:
      - "3000:3000"
    networks:
      - daas
    volumes:
    - ./client:/295B/client

  spark-master:
    image: spark-master
    container_name: spark-master
    build:
      context: ./processingServer
      dockerfile: ./Dockerfile
      target: "spark-master"
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - hadoop-workspace:/opt/workspace
    networks:
      - daas

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    build:
      context: ./processingServer
      dockerfile: ./Dockerfile
      target: "spark-worker"
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - hadoop-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - daas

  processingServer:
    build:
      context: ./processingServer
      dockerfile: ./Dockerfile
      target: "flask-server"
    image: flaskserver
    container_name: flaskserver
    depends_on:
      - spark-master
    ports:
      - "5000:5000"
    networks:
      - daas
    volumes:
      - ./processingServer:/usr/bin/spark-3.1.2-bin-hadoop3.2/295B/processingServer

volumes:
  hadoop-workspace:
    driver: local