version: '3'

networks:
  daas:
    external: false
    name: daas

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: server:node
    container_name: node_container
    ports:
      - "5001:5001"
    networks:
      - daas
    volumes:
      - ./server:/295B/server
    
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: client:react
    container_name: react_container
    ports:
      - "3000:3000"
    networks:
      - daas
    volumes:
    - ./client:/295B/client
  cassandra:
    image: 'bitnami/cassandra:latest'
    container_name: cassandra
    build:
      context: ./cassandra
      dockerfile: ./Dockerfile
    ports:
      - "9042:9042"
    environment:
      POSTGRES_USER: cassandra
      POSTGRES_PASSWORD: cassandra
    volumes:
      - ./cassandra:/data
    networks:
      - daas

  processingServer:
    build:
      context: ./processingServer
      dockerfile: ./Dockerfile
    image: spark:3.1.2
    container_name: spark_container
    ports:
      - "5000:5000"
    networks:
      - daas
    volumes:
      - ./processingServer:/home/jovyan/295B/processingServer
      