version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: server:node
    container_name: node_container
    ports:
      - "8001:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: client:react
    container_name: react_container
    ports:
      - "3001:3000"